### ISSUE TITLE
Raw socket error codes should start at 1

### ISSUE THREAD

**Issue by ecorm** [tavendo/WAMP#116]
The Advanced Profile spec says that the server can deny the connection and return an error code in the Router-to-Client reply, as follows:
0: serializer unsupported
1: maximum message length unacceptable
2: use of reserved bits (unsupported feature)
3: maximum connection count reached
4 - 15: reserved for future errors

However, there is a long-standing convention in C/C++ where an error code value of 0 represents "no error". In my upcoming C++ WAMP library, I use `std::error_code` to report errors, so I'm having to increment the returned error code by one in order to follow the convention that zero means "no error". It would be preferable if the library's error code value would match the one that was actually sent over the wire.

**Comment by oberstet** [comment]
changed now
