### ISSUE TITLE
ICallee.register documentation is wrong

### ISSUE THREAD

**Issue by Paranaix** [tavendo/WAMP#130]
The documentation of ICallee.register states that it can return "a list of Deferreds/Futures" whereas in fact the implementation in ApplicationSession returns a DeferredList. Either the documentation or the implementation is wrong.

**Comment by oberstet** [comment]
No, both are correct. Look at FutureMixin._gather_futures in its Twisted and asyncio flavor

**Comment by Paranaix** [comment]
Maybe you read the documention in a slightly different way than me but if thats the case it is definetely ambigious.

>When endpoint is an object, then each of the object’s methods that is decorated with autobahn.wamp.register() is automatically registered and a list of Deferreds/Futures is returned that each resolves or rejects as above.

The function DOES NOT return a list of Deferreds or Futures, it returns a DeferredList or a single Future. These are both simply objects not lists. 

Based on the quoted block above following code should run flawlessly:
```
for deferred in self.register(someObj):
    yield deferred
```

This is however not the case, instead one has to run it as:
```
results = yield self.register(someObj)
```

This important difference should be made clear in the documentation.

**Comment by beatgammit** [comment]
@Paranaix 

This repository is for the WAMP spec. AutobahnPython has its own [repository](https://github.com/tavendo/AutobahnPython), which (unless I'm mistaken) is where issues specific to that project should go.

**Comment by oberstet** [comment]
@Paranaix Ah, yes, the docs are ambigious. As @beatgammit notes, this isn't the correct repo though .. moved to https://github.com/tavendo/AutobahnPython/issues/322
