### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by IvaKom** [tavendo/WAMP#132]
The documentation reads:
>A Callee MAY request the disclosure of caller identity via
>
> ```
> CALL.Options.disclose_caller|bool := true
> ```
>Example
> ```
> [64, 927639114088448, {"disclose_caller":true}, "com.maypp.add2"]
> ```

I think it should rather say:
```
REGISTER.Options.disclose_caller|bool := true
```

**Comment by goeddea** [comment]
Thanks for the catch!
