### ISSUE TITLE
Black-/Whitelisting Receivers using authid/authrole

### ISSUE THREAD

**Issue by mbonneau** [tavendo/WAMP#134]
I would like to see a feature that would allow whitelisting by authid or authrole.

There are so many instances when applications would like to whitelist based on user. In order to do this they have to keep a map of which sessions belong to which authid. In order to remove this duplication of effort, it could just be built into the router.

**Comment by oberstet** [comment]
Funny, just discussed such a thing with Alex today. Yes. Essentially there are 3 dimensions to filter for:

* session IDs
* auth IDs
* auth roles

This should then work for both white- and blacklisting.

Do you have a specific proposal?

Also, how would that interact with https://github.com/tavendo/WAMP/issues/99 ?

The latter in general needs thinking about what multiple auth roles will mean for permissions ..

**Comment by Paranaix** [comment]
Isn't this something a Dealer or Broker should manage? A Dealer or Broker can always reject a request with a *not_authorized*  error. In my opinion this should rather a feature of a specific router than part of the spec. I think letting routers decide how they are configured allows for much greater flexibility than to have somethng like this in the spec.

**Comment by mbonneau** [comment]
@Paranaix 

I don't think of this feature so much as a security/authorization feature, but as a way to send events to specific subscribers/roles, or block specific subscribers/roles from receiving it.

A use case would be to subscribe to a private message URI that gets published to using an authid white list.

@oberstet -

As far as this relates to #99, having any whitelisted role would make you eligible except that belonging to any blacklisted role would override that. I do see how this behavior would complicate things when you have multiple authroles. I am, however, still in favor of multiple authroles.

**Comment by Paranaix** [comment]
Such a scenario can already be solved by embedding the authid in the uri and/or using pattern based subscribtions.

**Comment by oberstet** [comment]
In a way, yes. It would require wildcard pattern based permissions and matching one submatch to the sessions authid.

Am 13.02.2015 21:08 schrieb Sebastian Hoffmann <notifications@github.com>:

Such a scenario can already be solved by embedding the authid in the uri and/or using pattern based subscribtions.

**Comment by goeddea** [comment]
The use case of private channels could be solved as Tobias suggested. 

What can't easily be done is to exclude a user from receiving a message on a subscription which he shares with other users. For this you'd still need to track the sessions - and I agree with Matt that this is something that the router could more easily do.

With features, it's not that the router just has to offer what an application can't do in principle, but that it should also try to cover some common use cases (if it can do so without making the API too compilicated).

I think that more generally, we should have a way for a component to request information about users (via authID) and roles, e.g. a list of sessions for each. Having white/blacklisting based on these two dimensions, in addition to the existing sessionID, would then make the API more consistent and predictable.

**Comment by konsultaner** [comment]
A role-based black/white listing would be really handy if you think of a distributed router and business-logic-client system. In such a system you need to figure out what roles are allowed to sync messages between routers and business logic clients and what events are used to update the browser clients.

The current black/white-listing by sessionId requires the whole system to subscribe to [session meta events](https://github.com/tavendo/WAMP/blob/master/spec/advanced/session-meta-api.md). This causes a unnecessary traffic just to figure out what sessionIds to blacklist in a single event. Imagine a system with 20000 connected browsers. That would be a long message.

If the client itself can choose what roles are allowed to receive it's events, would make this situation very easy. The router would only have to filter by its session-role list.

**Comment by oberstet** [comment]
I am +1 on this too.

The relevant AP feature is: https://github.com/tavendo/WAMP/blob/master/spec/advanced/subscriber-blackwhite-listing.md

Currently, the `exclude` and `eligible` attributes is required to be a list of integers with WAMP session IDs, eg `{"exclude": [7891255, 1245751]}`.

`authid` and `authrole` are both strings.

Now, how do we add that without breaking existing implementations. Which I think should be a goal, in particular since this feature was marked "stable" for a long time. Consider:

1. `{"exclude": [7891255, 1245751, 9992342], "exclude_authrole": ["guest"], "exclude_authid": ["homer"]}`
2. `{"exclude": {"sessions": [7891255, 1245751, 9992342], "authroles": ["guest"], "authids": ["homer"]}}`

Both variants encode the same information.

Variant 2 makes `exclude`/`eligible` polymorphic (more effort to check) and breaks existing implementations (e.g. Autobahn will bail out because it does strict type checking on attributes).

Variant 1 is compatible. Existing implementations will just ignore the new `exclude_authrole` and `exclude_authid` attributes. It seems to be a bit smaller on the wire also.

**Comment by konsultaner** [comment]
In my opinion your naming is inconsistent. ```eliglebile``` should be ```eliglebile_sessionId``` and ```exclude``` should be ```exclude_sessionId``` which would break it again. I think version 2 is cleaner, makes it easier to handle for serializing and will not break if a shortcut version for the old notation is allowed but is depricated.

**Comment by oberstet** [comment]
> will not break if a shortcut version for the old notation is allowed

No, it _will_ break existing implementations which check the type for list.

In other words: any change to the name or type of the existing attribute will break implementations.

That means: we can't change `eligible` to `eligible_sessionids`, which granted, would better fit into naming.

As a minor note: we don't use mixed case in WAMP attributes.

**Comment by konsultaner** [comment]
+1 for Variant 1

**Comment by oberstet** [comment]
@mbonneau @Paranaix @goeddea The use case is clear and the feature well defined now. We have 2 votes for the concrete proposal (variant 1) above. What do you think / what's your vote pls?

**Comment by mbonneau** [comment]
I am +1 for variant 1.

**Comment by goeddea** [comment]
+1 for variant 1. Variant 2 is cleaner, but the difference is not big enough that it would justify breaking existing implementations.

**Comment by oberstet** [comment]
Ok, this is in the spec now https://github.com/tavendo/WAMP/blob/master/spec/advanced/subscriber-blackwhite-listing.md
