### ISSUE TITLE
Is WAMP a WebSocket subprotocol?

### ISSUE THREAD

**Issue by Vayel** [tavendo/WAMP#138]
According to [wamp.ws](wamp.ws) landing page, it is, but the [FAQ](http://wamp.ws/faq/#is_websocket_necessary_for_wamp) does not agree.

Thanks.

**Comment by Paranaix** [comment]
WAMP can run over websocket but it doesn't have to do so.

**Comment by Vayel** [comment]
So it isn't, is it?

**Comment by oberstet** [comment]
It is http://www.iana.org/assignments/websocket/websocket.xml#subprotocol-name
