### ISSUE TITLE
After-Authentication meta event

### ISSUE THREAD

**Issue by Paranaix** [tavendo/WAMP#146]
Yesterday we stumbled upon a major problem for our application. We are using crossbar as router and utilize a bunch of authentication methods. Upon successful authentication we create an internal session which is used all across our application. We also plan to perform security checks against the ip of the peer. To do this in one place and because we don't know whether authentication is successful in some of crossbars dynamic authenticators (e.g wampcra), we subscribe to `wamp.session.on_join` and setup the session in the handler. However this comes with a problem: The WAMP session might be ready before we are done. As https://github.com/tavendo/WAMP/issues/145 is currently outstanding, regular clients call a `GetMyToken` method directly after authentication to acquire their session token. Usually this works fine, but in some cases that fails because the event handler which setups the session takes abit too long. If we consider the planned ip checks, this is also a major problem, as there is a theoretical and practical timeframe in which peers can perform actions as if they were fully authenticated, even though we haven't checked their ips yet.

Now how to solve this? To be honest, I'm not really sure. The case and issue described here probably arises in many applications, thus its common sense to put the solution in the standard. However adding another meta-event seems quite rendundant. To solve this usecase the `WELCOME` message must only be sent, after all subscribers are done processing. Although, some subscribers might only want to perform a simple log. Delaying the `WELCOME` message would be unneccesary in such a case. Therefor, I think that the current `wamp.session.on_join` should stay to allow one to implement behaviour as just described.

Your thoughts?

**Comment by oberstet** [comment]
Need to understand first: so you want to have the option to hook up app code to the router which gets called _after_ (successful) authentication, but _before_ the authenticated client gets `WELCOME` sent (and the wamp.session.on_join event fires)?

**Comment by Paranaix** [comment]
yes exactly

**Comment by oberstet** [comment]
In this case, this is a router implementation specific feature, not WAMP spec. Eg Crossbar.io has hooks for dynamic auth. and what you describe would be another hook.

**Comment by oberstet** [comment]
issue migrated to https://github.com/crossbario/crossbar/issues/297
