### ISSUE TITLE
Identify clients

### ISSUE THREAD

**Issue by Vayel** [tavendo/WAMP#148]
Is there a way to identify a client, *i.e.* a way to send it a message? For example, if I open several instances of a Web page (let's say, for an in-browser game), can I have two particular instances (*i.e.* players) communicating?

Thanks!

**Comment by goeddea** [comment]
Two instances can communicate, e.g. by each instance subscribing to a topic which is specific to it (a simple example `com.myapp.topic.4758843839` where `4758843839` is the sessionID of the instance).  The other instance then publishes to this topic.

You then need some app-level mechanism for discovering the session or sessions you need to message, e.g. a component which keeps track of the currently connected sessions, can connect these to users (a user may have more than one browser window open) and announces this to clients upon request.

Hope this answers you question. Closing this as it isn't really an issue. (It's still possible to discuss this further in the comments here, this just means it won't appear on our to-do lists anymore.)

In principle, something like this is better asked on the mailing list - https://groups.google.com/forum/#!forum/wampws

**Comment by Vayel** [comment]
Thanks! So, the only way to do this is to register dynamically-named procedures, isn't it?

**Comment by goeddea** [comment]
Dynamically named topics are one option.

What you can also do is to do the messaging via a backend, and limit the publishes from there.

The sending client needs to include something identifying the recipient in its publish (or RPC) to the backend. This could e.g. be a user name or userID. The backend then determines which sessions currently belong to the user and publishes an event limited to these. E.g., if user `goeddea` had two clients connected at the time, with sessionIDs `123` and `456`, then  the publish would be

`session.publish("com.myapp.private_channel", ["the message"], {}, { eligible: [ 123, 456] })`

In this case, though others are subscribed to `com.myapp.private_channel`,  only the two sessions listed under `eligible` receive the event.

**Comment by Vayel** [comment]
I didn't know the `eligible` option. Thanks a lot!
