### ISSUE TITLE
Bad message type ID in Publisher/Caller Identification examples

### ISSUE THREAD

**Issue by ecorm** [tavendo/WAMP#154]
In this example, under [Publisher Identification](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#publisher-identification):

```
[4, 239714735, {}, "wamp.error.option_disallowed.disclose_me"]
```

The message type ID is 4, which corresponds to `CHALLENGE`. I think message type ID 8 for `ERROR` is what was really intended.

The same mistake was done in [Caller Identification](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#caller-identification).

**Comment by goeddea** [comment]
Thanks for the catch!
