### ISSUE TITLE
Early drafts for features should be put in a separate incubator page (suggestion)

### ISSUE THREAD

**Issue by ecorm** [tavendo/WAMP#158]
Some sections are clearly "brain dumps" for experimental ideas and only end up confusing newcomers (like myself) who are trying to understand the advanced specifications. I suggest that such sections be extracted out of the advanced spec and put into a separate "idea incubator" page.

I'm sure that these incomplete ideas have merit, it's just that they get in the way of understanding the more stable features proposed in the advanced spec.

**Comment by oberstet** [comment]
Yes, I agree.

**Comment by ecorm** [comment]
You could also do something along the lines of IETF and their RFCs, or C++ and their proposal papers. Each new idea would have its own page, perhaps a GitHub Wiki page. After the idea is hashed out enough, is accepted, and becomes semi-stable, it then gets incorporated into the spec.

**Comment by estan** [comment]
+1, and I like the idea of a separate document per non-`[stable]` spec feature. Perhaps just as Wiki pages here on GitHub?

**Comment by goeddea** [comment]
This was done a while ago.
