### ISSUE TITLE
ERROR in response to YIELD message

### ISSUE THREAD

**Issue by jcelliott** [tavendo/WAMP#170]
Shouldn't the spec allow sending an ERROR message in response to a bad YIELD message? For example, if the callee sends a YIELD message with an invalid INVOCATION.Request, shouldn't it be notified with an ERROR message? The way the spec is currently worded the router will just silently eat the YIELD message.

**Comment by mulderr** [comment]
1. Why should the callee care?
1. What can it do upon accuiring the the knowledge that the YIELD was invalid? Is there anything?
1. Under what circumstances would a callee send an invalid YIELD except obvious implementation bugs?
1. I imagine most client libs would like to clear any left over state after YIELDing asap. How would the callee even know which YIELD/CALL the ERROR references? And if the state is kept then for how long?
1. Have you found a use case where this would be an issue?

**Comment by jcelliott** [comment]
I guess I hadn't really thought through the implications. My primary argument for it is symmetry, which isn't a particularly strong argument. I ran across this while implementing dealer logic and assumed that the spec allowed for it until I went back and checked. The only real use for it in practice would alerting the application/user that something has gone very wrong; but, as your point 2 implies, there isn't really anything the callee would do about it.

**Comment by mulderr** [comment]
Just to be clear I wasn't conclusively saying this is a bad idea. Only that I couldn't figure out how would it work in detail and what would be the end goal. If the only usage we can come up with is logging an error or notifiying the user then it doesn't seem to justify the cost. We could revisit this later is someone can come up with a real world use case.
