### ISSUE TITLE
Revise router section

### ISSUE THREAD

**Issue by oberstet** [tavendo/WAMP#172]
Currently, the router implementations section on the Web site provides 3 columns: Broker and Dealer role supported yes/no, and "Advanced Profile" supported yes/no.

We should remove Broker/Dealer, as **all** router implementations implement both roles. Though allowed by the spec, a router that only implements one of the roles is probably academic.

AP Profile support: better provide a concrete list of AP features supported by a router.

**Comment by ecorm** [comment]
See also #125.

**Comment by oberstet** [comment]
duplicate of #125
