### ISSUE TITLE
MsgPack out of Date

### ISSUE THREAD

**Issue by konsultaner** [tavendo/WAMP#173]
I currently implement a Java-Version of WAMP for a Project and I realized that the required MsgPack is outdated. There are no specs available for the version v5 only v6 or v7, which is the current version. Is MsgPack backward compatible or why has it not been updated yet? Can you provide the v5 specs at instead?

**Comment by oberstet** [comment]
I don't have the v5 spec around. Doesn't the MsgPack site archive their specs?

Anyway: the actual reason to require v5 was the addition of binary vs string distinction with that version of MsgPack.

Are v6 and v7 upwards compatible? In that case, we could clarify in the WAMP spec: "v5 or later"

**Comment by oberstet** [comment]
On a sidenote - curious: why do you feel the need to write a WAMP implementation? https://github.com/Matthias247/jawampa doesn't cut it?

**Comment by konsultaner** [comment]
I need to have my own integration because the jawampa does not support features I need. And the protocoll itself is easy to implement. I need a more complex server system to be able to distribute multiple servers including wamp over tcp and other things.

I have no idea if MagPack is somehow downwards compatiple. I couldn't find it out. I think the best Idea is to update the specs to of wamp to v7 and fork it for all languages.

**Comment by konsultaner** [comment]
by the way jawampa [uses v.0.7.0](https://github.com/Matthias247/jawampa/blob/b64d72642647c378ee8d3bde142ec233368b1af2/jawampa-core/pom.xml#L57)
