### ISSUE TITLE
make authId required for the whole auth process

### ISSUE THREAD

**Issue by konsultaner** [tavendo/WAMP#175]
Imagine you have multiple clients connected to a loadbalancer that connects to multiple servers. These servers connect to an extra authentication server. It is not possible to determine which challange needs to be send to which client due to asynchronous reasons, when the authserver only uses the auth-WAMP-Messages for the communication. The only workaround would be to have a separate auth-process between the servers and the auth-servers with a different protocoll, which would result in an extra overhead.

So adding a authId to Challenge,Authenticate and Welcome would be handy. 

For now I'll handle it by prefixing a messageId when sending the messages.

**[UPDATE] This might help as well**
> Implementations MAY define and use implementation specific messages with message type codes from the extension message range [256, 1023]. For example, a router MAY implement router-to-router communication by using extension messages.

**Comment by oberstet** [comment]
we won't change WAMP-CRA anymore at this stage

**Comment by oberstet** [comment]
ah, and the authid is part of WELCOME https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#challenge-response-authentication
