### ISSUE TITLE
caller black/white listing

### ISSUE THREAD

**Issue by konsultaner** [tavendo/WAMP#181]
As a counterparts to the subscriber black/white listing there should be the same possibility for callers. 

There are different ways to achieve that result with available advanced features like caller_identification and the session_meta api. But as discussed in the issue #134 this will end up in a huge message overhead when it comes to a distribued system of multiple routers and business-logic clients.

If you take a look at a MVC framework which basicly only provides RPCs, the Router is responsible for filtering requests by authroles/sessionIds. The method (callee) itself is not deciding wether a session/authrole is allowed to execute it.

As the business logic is inside the callee, it should now about who is allowed to call it, but it should propagate its availability to the router to somehow follow the [uniform access princible](https://en.wikipedia.org/wiki/Uniform_access_principle) and reduce message overheads.

Thats why I would love to see this in the specs:

    REGISTER.Options.exclude|list
    REGISTER.Options.eligible|list
    REGISTER.Options.exclude_authid|list
    REGISTER.Options.eligible_authid|list
    REGISTER.Options.exclude_authrole|list
    REGISTER.Options.eligible_authrole|list

**Comment by oberstet** [comment]
We had that previously in the spec (only exclude/eligible based on session ID) and even implemented in CB, but removed it again. The reason: no valid use case.

Do you have a concrete use case?

**Comment by oberstet** [comment]
also note: I guess you ment callee, not caller bw-listing ..

**Comment by konsultaner** [comment]
I renamed it.

As you might have recognized, I'm in the middle of a WAMP-Integration that uses distributed/scaleable peers. I need to avoid synchronization in this scenario to/and reduce message overheads. Because I need really high performance.

The structure is:

    BrowserClient <--> Router <--> BusinessLogicClient
                         ||
                     AuthServer

**Scenario with the current WAMP specs:**
BrowserClient authenticates and receives a sessionId stored to one of n routers. The BrowserClient now calls a RPC. Neither the callee nor the router do know wether the caller is allowed to receive an answer, because the callee does not know the callers authrole and the router has no ability to filter by authrole. caller_identification needs to be turned on. The callee has to ask the router for the callers role by using the session_meta_api. Which cost 2 extra messages and some more bytes for the caller_identification for every call. An optimization would be to store the session-role-association once the callee had send a call. This would cause a state in the clients that should be avoided for scaleable systems.

**Scenario with caller blacklisting as discribed:**
The callee registers the remote procedure to one of n router excluding a role. BrowserClient authenticates and receives a sessionId stored to one of n routers. The BrowserClient does a rpc without having that role. The router would instandly deny the request and safe 4 Messages (Invocation,2xSessionMetaApi,Error to Router). If the router was a router the callee did not registered to, the router could forward the message to another router that has a registration. But this is another story.

**Comment by oberstet** [comment]
> I ment caller. 

That doesn't make sense. Restricting callers is the job of authorization.

Callers correspond to Publishers, and Callees correspond to Subscribers.

A Publisher black-white-lists the target of it's publication: the set of receivers is reduced from Subscribers.

A Caller black-white-lists the target of it's call: the set of considered receivers is reduced from Callees.

And also, the whole feature of "callee bw listing" only makes sense with "shared registrations", as only then there is more than 1 potential target for a given call.

**Comment by konsultaner** [comment]
Sorry, yes callee is right!!!

> Restricting callers is the job of authorization.

This is absolutly right. The router needs to do that. But only the callee knows what roles are allowed to call its procedures. The router should only know the authmethod/server. This way you can have replaceable clients. Kind of like exchangable storm topologies that use the same nimbus.

**Comment by oberstet** [comment]
> only the callee knows what roles are allowed to call its procedures

No, the router should do any authorization which isn't dependent on application payload.

Here is a valid use case for providing authrole in caller details to callees:

Consider a "place order" procedure. The procedure should be callable only by users with authrole "sales". This can be done by the router alone. However, if the procedure should only allow "place order" for role "sales" if amount < 1000, and allow "place order" for role "manager" if amount >= 1000, then this requires authorization in "place order". And then "place order" procedure needs to know the authrole of the caller.

rgd the question which details to disclose: https://github.com/tavendo/WAMP/issues/57

**Comment by konsultaner** [comment]
I do understand why you want to keep it like it is after reading #57. But Imagine a WAMP-PaaS providing an interface to an authserver and custom clients. This is impossible to achieve without passing a configuration list of allowed authrole-procedure associations.

And still you provide this feature to subscribers, that receive business logic events, but not not callers that receive business logic responses. You could mimic pubSub with progressive events where a subscriber would be equal to callers.

**Comment by oberstet** [comment]
I have no clue what you are talking about ..
