### ISSUE TITLE
Let the callee decide by protocol who calls it 

### ISSUE THREAD

**Issue by konsultaner** [tavendo/WAMP#184]
At the moment only the router is responsible to decide whether a caller is allowed to call a callees remote procedures or not. But the router should be a black box that could be a part of any scenario without the need of extra router logic. Also the router should be interchangeable for a general WAMP implementation.

The WAMP-Protocol itself does not explicitly support the three listed requirements in my eyes. 

The crossbar.io implementation supports a [dynamic and static](http://crossbar.io/docs/Authorization/) way to tell the router who is allowed to call a certain procedure and who isn't. The dynamic approach makes it not interchangeable with another implementation out of the box.

If the message Register had a caller black/white listing as written in issue #181, the router would have to implement a behavior where the callee decides on registration who is allowed to call it's methods and who isn't.

This is very similar to some MVC implementations where the callee is kind of equal to a controller. The following pseudo code shows a callee with an annotated method to make it clearer.

    class Callee {

        @roles(someRole1,someRole2)
        void myMethod(){
             ....
        }

    }

**Comment by Paranaix** [comment]
Totally supporting this. EJBs use a nearly identical approach (see http://openejb.apache.org/security-annotations.html).

**Comment by oberstet** [comment]
> At the moment only the router is responsible to decide whether a caller is allowed to call a callees remote procedures or not.

Correct. That's how it should be. The router is the only trusted party, and it enforces any authorization that is independent of app payload. Authorization that depends on app payload needs to be in user code, means: callee.

> Also the router should be interchangeable for a general WAMP implementation.

https://github.com/tavendo/WAMP/blob/master/spec/basic.md#router-implementation-specifics

@Paranaix If EJBs do something, it's almost certainly wrong;) Big committee, enterprise shit that doesn't work.

**Comment by ecorm** [comment]
Perhaps there should be a standardized meta-api for authentication management? That would solve the problem of the router not being interchangeable.

**Comment by oberstet** [comment]
@ecorm The AP has a meta API defined at the **WAMP level**, but not at the **router level** and I wouldn't support the latter in the spec in any way. A router level API is router specific by definition.  Both authentication and authorization schemes and mechanisms are *explicitly* stated as implementation specific in the spec.

**Comment by ecorm** [comment]
> Both authentication and authorization schemes and mechanisms are _explicitly_ stated as implementation specific in the spec.

Ah, I had either overlooked or forgotten that statement. What might end up happening is whatever Crossbar does for the "router-level API" would be become a _defacto_ standard imitated by other implementations.

Perhaps such a router-level API could become standardized in WAMP v3?

**Comment by oberstet** [comment]
> ... whatever Crossbar does for the "router-level API" would be become a defacto standard imitated by other implementations.

This is unlikely to happen for _different_ reasons. The management API of Crossbar goes beyond Crossbar itself. Don't waste your time on replicating Crossbar 1:1 - believe me. The WAMP spec is already quite broad and deep, and serves as a common ground on top of which there is still enough room for _all_ to innovate and specialize. An ecosystem collapsing to a singularity isn't healthy, and isn't a real ecosystem.

> Perhaps such a router-level API could become standardized in WAMP v3?

As said, I wouldn't support that.

**Comment by konsultaner** [comment]
> The router is the only trusted party, and it enforces any authorization that is independent of app payload.

@oberstet where is the difference (security wise) between the [router asking the business logic client](http://crossbar.io/docs/Authorization/#dynamic-authorization) what it should authorize and the business logic client telling the router directly who is allowed to.

    Crossbar 
    ROUTER ----------tell me!----------->Client
                                            |
           <-------this is allowed----------

    Other approach
    Client ------------ Register[this is allowed]-----------> Router

**Comment by oberstet** [comment]
The difference is:

1. with dynamic authorization, the Crossbar administrator stays in control and still decides if and for what URIs a dynamic authorizer component is consulted
2. the dynamic authorizer component centralizes authorization code
3. the dynamic authorizer component can be guarded

None of above is the case if you distribute authorization code all over your actual business components.

There is only one valid use case where authorization code must reside in the actual business component being called: and that is if the authorization depends on the app payload (args/kwargs)

E.g my example with place order being allowed/disallowed depending on the order amount.

If you need that, it's the callee's (business component) responsibility to allow/deny.

As in: routers must not bother with app payload. Crossbar is design to follow that strictly. It will only touch the app payload for 2 reasons:

* convert between different serialization formats
* validate the application payload against a configured schema (an unreleased feature of CB, where you configure JSON schemata on URIs, and CB will validate the payload against that).

Again, I don't care at all what EJBs or what do or did or plan to do. They can do whatever they want. As we can do with WAMP here. But I do care massively about upholding the integrity and coherence of the design principles of WAMP.

**LAST**: All the discussion above is specific to CB and shouldn't happen here.

**Comment by konsultaner** [comment]
> LAST: All the discussion above is specific to CB and shouldn't happen here.

I didn't want to discuss CB here, but it implements WAMP by it's principles. So I needed to find out the difference. And maybe your are right ;)

**Comment by oberstet** [comment]
Let me note one thing: the casual reader of above thread might come to the conclusion that I would be very stubborn person who doesn't listen to others. I'd say: that would be a wrong impression. I do have strong opinions - in some aspects, and for a reason (obviously, all my view). If you look into the history of WAMP, the mailing list and the issue tracker, you can see that lot's of very fine feedback, suggestions and ideas of others went into WAMP that came from others. Again: WAMP would never be as nice without the community approach.

Granted that you will also see that there are a couple of aspects where I am not ready for any compromise at all. And this is the case when the underlying design principles of WAMP are at stake. If I'd give in on those, then it's only a matter of time when WAMP would sink into an incoherent mess. Well, if you disagree on this approach, I am afraid, you would need to look elsewhere or fork WAMP, which you very much can do. Note that you can't call it "WAMP" then, as we hold a trademark on that, and will enforce it. Again to uphold integrity (users would be confused about the "real" WAMP). But you can still take a free ride on all the work we did;) It's open-source / open-content!

**Comment by konsultaner** [comment]
I think it is important to have a supervisor that has the knowledge about all that happens to the project. If you mean me by this :

> Well, if you disagree on this approach, I am afraid, you would need to look elsewhere or fork WAMP, which you very much can do.

then you are misunderstanding my discussion here. I'm just adding input to the community while devloping stuff with WAMP.

**Comment by oberstet** [comment]
@konsultaner Ah, great to hear! No, I wasn't referring to you in particular, I just wanted to mention these things .. for readers that might stumble across the thread and might get irritated. All fine.
