### ISSUE TITLE
Are multiple sessions/realms per peer possible?

### ISSUE THREAD

**Issue by konsultaner** [tavendo/WAMP#185]
Imagine you have some backend clients that need to work with two or more realms. How should the clients do that?

- by connect/disconnect to switch between realms
- the router must be able to handle multiple sessions per transport and
    - all incomming yields and events belong to all sessions/realms
    - therefore the procedures/topics need to have separate namespaced uri strings for the different realms

or is there another way to do it right?

**Comment by goeddea** [comment]
Not sure I understand the question, but a client can establish several connections/sessions - with a single router or multiple routers. Each of these connections/sessions can be connected to a different realm, so that backend components working with multiple realms is not a problem.

**Comment by oberstet** [comment]
yes, simply open multiple, concurrent connections
