### ISSUE TITLE
Describe Raw transport

### ISSUE THREAD

**Issue by oberstet** [tavendo/WAMP#63]
WAMP can run over Raw transports instead of WebSocket.

Each message is prefixed with a `uint32` (big endian) that provides the (serialized) length of the following WAMP message.

This works for both JSON and MsgPack serialization.

**Comment by oberstet** [comment]
this is in the spec for some time now

**Comment by konsultaner** [comment]
@oberstet I just saw [this on Stackoverflow](https://stackoverflow.com/questions/14174184/what-is-the-mask-in-a-websocket-frame#answer-14174429).

>By having the browser generate a random mask for each frame, the hostile client code cannot choose the byte patterns that appear on the wire and use that to attack vulnerable network infrastructure.

Shouldn't have RawSockets a mask as well?

**Comment by oberstet** [comment]
no, because a) browser cannot talk rawsocket, and b) everything should run over TLS anyways
